-keep @nibel.runtime.EntryFactoryProvider public class **
-keepclassmembers @nibel.runtime.EntryFactoryProvider class ** { public <methods>; }
-keepnames public class * extends nibel.annotations.ExternalDestination
