package nibel.annotations

import android.os.Parcelable

/**
 * A base type for all navigation destinations.
 */
sealed interface Destination

/**
 * A base type for destinations for external multi-module navigation.
 */
sealed interface ExternalDestination : Destination

/**
 * An external destination type for screens with no arguments.
 * Each descendant of [DestinationWithNoArgs] must be associated with exactly one screen annotated
 * with [UiExternalEntry].
 */
interface DestinationWithNoArgs : ExternalDestination

/**
 * An external destination type for screens with arguments.
 * Each descendant of [DestinationWithArgs] must be associated with exactly one screen annotated
 * with [UiExternalEntry].
 */
interface DestinationWithArgs<A : Parcelable> : ExternalDestination {
    /**
     * Type-safe `Parcelable` args for the screen.
     */
    val args: A
}

/**
 * An external destination type for screens that return a result.
 *
 * This interface should be implemented by destinations whose associated screens return
 * a result to their caller. When a destination implements this interface, callers can
 * use `NavigationController.navigateForResult()` to receive type-safe results.
 *
 * The result type [TResult] must be [Parcelable] and match the `result` parameter
 * specified in the associated [UiExternalEntry] annotation.
 *
 * Example:
 * ```
 * @Parcelize
 * data class PhotoResult(val uri: String) : Parcelable
 *
 * // Destination with no args but with result
 * object PhotoPickerDestination : DestinationWithNoArgs, DestinationWithResult<PhotoResult>
 *
 * // Destination with both args and result
 * data class EditPhotoDestination(
 *     override val args: EditPhotoArgs
 * ) : DestinationWithArgs<EditPhotoArgs>, DestinationWithResult<PhotoResult>
 *
 * // Associated screen
 * @UiExternalEntry(
 *     type = ImplementationType.Composable,
 *     destination = PhotoPickerDestination::class,
 *     result = PhotoResult::class
 * )
 * @Composable
 * fun PhotoPickerScreen(navigator: NavigationController) {
 *     // ... photo selection UI
 *     navigator.setResultAndNavigateBack(PhotoResult(selectedUri))
 * }
 *
 * // Caller from another feature module
 * navigator.navigateForResult(PhotoPickerDestination) { result: PhotoResult? ->
 *     result?.let { /* handle result */ }
 * }
 * ```
 *
 * @param TResult The type of result returned by the screen (must be [Parcelable])
 *
 * @see UiExternalEntry
 * @see DestinationWithNoArgs
 * @see DestinationWithArgs
 */
interface DestinationWithResult<TResult : Parcelable> : ExternalDestination {
    /**
     * The runtime [Class] of the result type.
     * Used for type checking and result delivery at runtime.
     *
     * This property is typically implemented by the code generator or can be
     * provided as a default implementation.
     */
    val resultType: Class<TResult>
        get() = throw NotImplementedError(
            "resultType must be implemented. " +
                "This is typically generated by the compiler for destinations with results.",
        )
}

/**
 * A base type for destinations for internal single-module navigation.
 */
interface InternalDestination : Destination
